spring.application.name=student-management

# S\u1eed d\u1ee5ng DATABASE_PUBLIC_URL t\u1eeb \u1ea3nh c\u1ee7a b\u1ea1n
# L\u01b0u \u00fd: Ph\u1ea3i th\u00eam ti\u1ec1n t\u1ed1 "jdbc:" v\u00e0o tr\u01b0\u1edbc url c\u1ee7a Railway
spring.datasource.url=jdbc:postgresql://66.33.22.253:31655/railway?options=-c%20timezone=UTC&forceBinary=true
spring.datasource.username=postgres
spring.datasource.password=mxKgPwtEjvQWsuVFylpSNuPZpiyFFles
spring.datasource.driver-class-name=org.postgresql.Driver

# C\u1ea5u h\u00ecnh Hibernate \u0111\u1ec3 t\u1ef1 \u0111\u1ed9ng t\u1ea1o b\u1ea3ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# C\u1ea5u h\u00ecnh encoding \u0111\u1ec3 tr\u00e1nh l\u1ed7i font ti\u1ebfng Vi\u1ec7t
spring.datasource.sql-script-encoding=UTF-8